{{- if .Values.npuExporter.enabled }}
{{- if or
(eq (include "hasNpuType" (list "910" .Values.global.npuType)) "true")
(eq (include "hasNpuType" (list "310" .Values.global.npuType)) "true")
(eq (include "hasNpuType" (list "310p" .Values.global.npuType)) "true")
}}
apiVersion: v1
kind: Namespace
metadata:
  name: npu-exporter
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: exporter-network-policy
  namespace: npu-exporter
spec:
  podSelector:
    matchLabels:
      app: npu-exporter
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app: prometheus
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app: prometheus
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: npu-exporter
  namespace: npu-exporter
spec:
  selector:
    matchLabels:
      app: npu-exporter
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      labels:
        app: npu-exporter
      {{- if .Values.npuExporter.additionalLabels }}
        {{- toYaml .Values.npuExporter.additionalLabels | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.npuExporter.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        {{- include "initContainer.createDir" (dict 
          "path" (include "extractPath" .Values.npuExporter.args.logFile)
          "owner" "root:root"
          "mountPath" "/var/log/mindx-dl"
        ) | nindent 8 }}
      containers:
        - name: npu-exporter
          image: {{ .Values.npuExporter.image.repository | default (printf "%s/%s" .Values.global.imageRegistry "npu-exporter") }}:{{ .Values.npuExporter.image.tag | default .Values.global.imageTag }}
        {{- with .Values.npuExporter.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          imagePullPolicy: {{ .Values.npuExporter.image.pullPolicy | default .Values.global.imagePullPolicy }}
          command: [ "/bin/bash", "-c", "--"]
          args:
          - umask 027
          - npu-exporter
          {{- include "extraArgs" .Values.npuExporter.args | indent 10 }}
        {{- with .Values.npuExporter.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          ports:
          - name: http
            containerPort: {{ .Values.npuExporter.args.port }}
            protocol: TCP
          volumeMounts:
          - name: log-npu-exporter
            mountPath: {{ .Values.npuExporter.args.logFile | include "extractPath" }}
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - name: ascend-driver
            mountPath: /usr/local/Ascend/driver
            readOnly: true
          - name: ascend-dcmi
            mountPath: /usr/local/dcmi
            readOnly: true
          - name: sys
            mountPath: /sys
            readOnly: true
          - name: tmp
            mountPath: /tmp
        {{- if eq .Values.npuExporter.args.containerMode "isulad" }}
          - name: isulad
            mountPath: /run/isulad.sock
        {{- else }}
          - name: containerd
            mountPath: /run/containerd
            readOnly: true
        {{- end }}
        {{- if and (eq .Values.npuExporter.args.containerMode "docker") (not .Values.npuExporter.mountSock) }}
          - name: docker-shim
            mountPath: /var/run/dockershim.sock
            readOnly: true
          - name: docker
            mountPath: /var/run/docker
          {{- if eq .Values.global.containerMode "cri-docker" }}
          - name: cir-dockerd
            mountPath: /var/run/cri-dockerd.sock
            readOnly: true
          {{- end }}
        {{- else if and (eq .Values.npuExporter.args.containerMode "docker") (.Values.npuExporter.mountSock) }}
          - name: sock
            mountPath: {{ .Values.npuExporter.args.mountSockPath }}
        {{- end }}
      volumes:
      - name: mindx-dl-log
        hostPath:
          path: /var/log/mindx-dl
          type: DirectoryOrCreate
      - name: log-npu-exporter
        hostPath:
          path: {{ .Values.npuExporter.args.logFile | include "extractPath" }}
          type: Directory
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: ascend-driver
        hostPath:
          path: /usr/local/Ascend/driver
      - name: ascend-dcmi
        hostPath:
          path: /usr/local/dcmi
      - name: sys
        hostPath:
          path: /sys
        readOnly: true
      - name: tmp
        hostPath:
          path: /tmp
    {{- if eq .Values.npuExporter.args.containerMode "isulad" }}
      - name: isulad
        hostPath:
          path: /run/isulad.sock
    {{- else }}
      - name: containerd
        hostPath:
          path: /run/containerd
    {{- end }}
    {{- if and (eq .Values.npuExporter.args.containerMode "docker") (not .Values.npuExporter.mountSock) }}
      - name: docker-shim
        hostPath:
          path: /var/run/dockershim.sock
      - name: docker
        hostPath:
          path: /var/run/docker
      {{- if eq .Values.global.containerMode "cri-docker" }}
      - name: cir-dockerd
        hostPath:
          path: /var/run/cri-dockerd.sock
      {{- end }}
    {{- else if and (eq .Values.npuExporter.args.containerMode "docker") (.Values.npuExporter.mountSock) }}
      - name: sock
        hostPath:
          path: {{ .Values.npuExporter.args.mountSockPath }}
    {{- end }}
{{- end }} 
{{- end }}  
