{{- if .Values.noded.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: noded
  namespace: mindx-dl
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-noded-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-noded-rolebinding
subjects:
  - kind: ServiceAccount
    name: noded
    namespace: mindx-dl
roleRef:
  kind: ClusterRole
  name: pods-noded-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: noded
  namespace: mindx-dl
spec:
  selector:
    matchLabels:
      app: noded
  template:
    metadata:
      labels:
        app: noded
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
    {{- with .Values.noded.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: noded
      initContainers:
        {{- include "initContainer.createDir" (dict 
          "path" (include "extractPath" .Values.noded.args.logFile)
          "owner" "root:root"
          "mountPath" "/var/log/mindx-dl"
        ) | nindent 8 }}
      containers:
        - name: noded
          image: {{ .Values.noded.image.repository | default (printf "%s/%s" .Values.global.imageRegistry "noded") }}:{{ .Values.noded.image.tag | default .Values.global.imageTag }}
        {{- with .Values.noded.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          imagePullPolicy: {{ .Values.noded.image.pullPolicy | default .Values.global.imagePullPolicy }}
          command: [ "/bin/bash", "-c", "--" ]
          args:
          - |
            /usr/local/bin/noded {{ include "extraArgs" .Values.noded.args }}
        {{- with .Values.noded.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          volumeMounts:
          - name: log-noded
            mountPath: {{ .Values.noded.args.logFile | include "extractPath" }}
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true 
          {{- with .Values.noded.extraVolumeMounts }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
      volumes:
      - name: mindx-dl-log
        hostPath:
          path: /var/log/mindx-dl
          type: DirectoryOrCreate
      - name: log-noded
        hostPath:
          path: {{ .Values.noded.args.logFile | include "extractPath" }}
          type: Directory
      - name: localtime
        hostPath:
          path: /etc/localtime
      {{- with .Values.noded.extraVolumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}                  
{{- end }}