{{- if .Values.resilienceController.enabled }}
{{- if .Values.resilienceController.useServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: resilience-controller
  namespace: mindx-dl
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-resilience-controller-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
  - apiGroups: ["batch.volcano.sh"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "watch", "delete"]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get" ]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resilience-controller-rolebinding
subjects:
  - kind: ServiceAccount
    name: resilience-controller
    namespace: mindx-dl
roleRef:
  kind: ClusterRole
  name: pods-resilience-controller-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resilience-controller
  namespace: mindx-dl
spec:
  replicas: {{ .Values.resilienceController.replicas | default 1 }}
  selector:
    matchLabels:
      app: resilience-controller
  template:
    metadata:
      labels:
        app: resilience-controller
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
    {{- with .Values.resilienceController.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.resilienceController.useServiceAccount }}
      serviceAccountName: resilience-controller
    {{- else }}
      automountServiceAccountToken: false
    {{- end }}
      initContainers:
        {{- include "initContainer.createDir" (dict 
          "path" (include "extractPath" .Values.resilienceController.args.logFile)
          "owner" "hwMindX:hwMindX"
          "mountPath" "/var/log/mindx-dl"
        ) | nindent 8 }}
      containers:
        - name: resilience-controller
          image: {{ .Values.resilienceController.image.repository | default (printf "%s/%s" .Values.global.imageRegistry "resilience-controller") }}:{{ .Values.resilienceController.image.tag | default .Values.global.imageTag }}
        {{- with .Values.resilienceController.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
        {{- end }}    
          imagePullPolicy: {{ .Values.resilienceController.image.pullPolicy | default .Values.global.imagePullPolicy }}
          command: [ "/bin/bash", "-c", "--"]
        {{- if .Values.resilienceController.useServiceAccount }}
          args:
          - |
            umask 027
            /home/hwMindX/resilience-controller {{ include "extraArgs" .Values.resilienceController.args }}
        {{- else }}
          args:
          - |
            umask 027
            export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/hwMindX/lib
            /home/hwMindX/resilience-controller {{ include "extraArgs" .Values.resilienceController.args }}
        {{- end }}
        {{- with .Values.resilienceController.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          volumeMounts:
          - name: log
            mountPath: {{ .Values.resilienceController.args.logFile | include "extractPath" }}
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
        {{- if not .Values.resilienceController.useServiceAccount }}
          - name: kmckeystore
            mountPath: /etc/mindx-dl/kmc_primary_store
          - name: kmckeybak
            mountPath: /etc/mindx-dl/.config
          - name: kmc-resilience
            mountPath: /etc/mindx-dl/resilience-controller
        {{- end }}
      volumes:
      - name: mindx-dl-log
        hostPath:
          path: /var/log/mindx-dl
          type: DirectoryOrCreate
      - name: log
        hostPath:
          path: {{ .Values.resilienceController.args.logFile | include "extractPath" }}
          type: Directory
      - name: localtime
        hostPath:
          path: /etc/localtime
    {{- if not .Values.resilienceController.useServiceAccount }}
      - name: kmckeystore
        hostPath:
          path: /etc/mindx-dl/kmc_primary_store
          type: DirectoryOrCreate
      - name: kmckeybak
        hostPath:
          path: /etc/mindx-dl/.config
          type: DirectoryOrCreate
      - name: kmc-resilience
        hostPath:
          path: /etc/mindx-dl/resilience-controller
          type: DirectoryOrCreate
    {{- end }}
{{- end }}